FROM    almalinux:9

ARG     RUNNERREPO="https://github.com/actions/runner" RUNNERPATCH SDK=8 SDK_VERSION ARCH

RUN     echo "tsflags=nodocs" >>/etc/dnf/dnf.conf

RUN     dnf update -y -q && \
        dnf install -y -q wget git which langpacks-en glibc-all-langpacks sudo
        
RUN     dnf install -y -q dotnet-sdk-${SDK}.0 && \
        SDK_VERSION=`dotnet --version` && \
        echo "Using SDK - ${SDK_VERSION}"

ADD    ${RUNNERPATCH} /tmp/runner.patch

RUN     cd /tmp && \
        git clone --tags -q ${RUNNERREPO} && \
        cd runner && \
        git checkout $(git tag --sort=-v:refname | grep '^v[0-9]' | head -n1) && \
        git apply --whitespace=nowarn /tmp/runner.patch && \
        sed -i'' -e /version/s/8......\"$/8.0.100\"/ src/global.json

RUN     cd /tmp/runner/src && \
        ./dev.sh layout && \
        ./dev.sh package && \
        ./dev.sh test && \
        rm -rf /root/.dotnet /root/.nuget

RUN     useradd -c 'Action Runner' -m -s /bin/bash runner && \
        usermod -L runner && \
        echo 'runner ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/runner && \
        chmod 440 /etc/sudoers.d/runner

RUN     mkdir -p /opt/runner && \
        tar -xf /tmp/runner/_package/*.tar.gz -C /opt/runner && \
        chown -R  runner: runner /opt/runner && \
        su -c "/opt/runner/config.sh --version"  runner

RUN     dnf install -y -q cmake make automake autoconf m4 gcc gcc-c++ libtool epel-release

RUN     rm -rf /tmp/runner /var/cache/dnf/* /tmp/runner.patch \
        dnf clean all
    
USER     runner

EXPOSE  443

CMD     /bin/bash
